# Notebook for merging and cleaning deidentified "book a librarian" export data

In [1]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import matplotlib as plt
import seaborn as sns
import plotly.express as px
import openpyxl

In [2]:
## create dataframes for book a librarian datasets

# 2022-2023
df_book2223Q1 = pd.read_excel('/home/ekmys/PycharmProjects/Your-Library-Your-Impact/data/Book A Librarian Export Q1 AY22-23 - Deidentified.xlsx')
df_book2223Q2 = pd.read_excel('/home/ekmys/PycharmProjects/Your-Library-Your-Impact/data/Book A Librarian Export Q2 AY22-23 - Deidentified.xlsx')
df_book2223Q3 = pd.read_excel('/home/ekmys/PycharmProjects/Your-Library-Your-Impact/data/Book A Librarian Export Q3 AY22-23 - Deidentified.xlsx')
df_book2223Q4 = pd.read_excel('/home/ekmys/PycharmProjects/Your-Library-Your-Impact/data/Book A Librarian Export Q4 AY22-23 - Deidentified.xlsx')

# 2023-2024
df_book2324Q1 = pd.read_excel('/home/ekmys/PycharmProjects/Your-Library-Your-Impact/data/Book a Librarian Export Q1 AY23-24 - Deidentified.xlsx')
df_book2324Q2 = pd.read_excel('/home/ekmys/PycharmProjects/Your-Library-Your-Impact/data/Book a Librarian Export Q2 AY23-24 - Deidentified.xlsx')
df_book2324Q3 = pd.read_excel('/home/ekmys/PycharmProjects/Your-Library-Your-Impact/data/Book a Librarian Export Q3 AY23-24 - Deidentified.xlsx')
df_book2324Q4 = pd.read_excel('/home/ekmys/PycharmProjects/Your-Library-Your-Impact/data/Book a Librarian Export Q4 AY23-24 - Deidentified.xlsx')

# 2024-2025
df_book2425Q1 = pd.read_excel('/home/ekmys/PycharmProjects/Your-Library-Your-Impact/data/Book a Librarian Export Q1 AY24-25 - Deindentified.xlsx')
df_book2425Q2 = pd.read_excel('/home/ekmys/PycharmProjects/Your-Library-Your-Impact/data/Book a Librarian Export Q2 AY24-25 - Deidentified.xlsx')
df_book2425Q3 = pd.read_excel('/home/ekmys/PycharmProjects/Your-Library-Your-Impact/data/Book a Librarian Export Q3 AY24-25 - Deidentified.xlsx')
df_book2425Q4 = pd.read_excel('/home/ekmys/PycharmProjects/Your-Library-Your-Impact/data/Book a Librarian Export Q4 AY24-25 - Deidentified.xlsx')

In [3]:
# concatenate into one dataframe
frames = [df_book2223Q1, df_book2223Q2, df_book2223Q3, df_book2223Q4,
          df_book2324Q1, df_book2324Q2, df_book2324Q3, df_book2324Q4,
          df_book2425Q1, df_book2425Q2, df_book2425Q3, df_book2425Q4]
df_book_all = pd.concat(frames, axis=0)
df_book_all.head()

,Date,Service,Location,Duration (mins.),Signed Up Attendees Count,Custom Fields.1,Custom Fields.2,Custom Fields.3,Event Type,Booking Id,...,Column4,Column5,Column6,Column7,PNWU Status,PNWU Academic Affiliation,Virtual/Library Meeting,Tell us about your research project,PNWU Status,Tells us about your research project
0,2022-07-01,Research Consultation,Virtual,60,1,{ PNWU Status: Student,PNWU Academic Affiliation: DO,Tell us about your research project in 3 sen...,Single,AAMkAGM1ZDA4MDNjLTUyOWUtNGVlNi04ZmZmLTU5NTU5OD...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-07-06,Research Consultation,Virtual,60,1,{ PNWU Status: Student,PNWU Academic Affiliation: DO,Tell us about your research project in 3 sen...,Single,AAMkAGM1ZDA4MDNjLTUyOWUtNGVlNi04ZmZmLTU5NTU5OD...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022-07-11,Special Project/Collaboration,PNWU Library or Virtual,60,1,{ PNWU Academic Affiliation: Other,PNWU Status: Other,Tell us your idea in 2 sentences or keep it ...,Single,AAMkAGM1ZDA4MDNjLTUyOWUtNGVlNi04ZmZmLTU5NTU5OD...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022-07-12,Library Access Orientation,Virtual,30,1,{ PNWU Academic Affiliation: DO,PNWU Status: Fulltime Faculty,Tell us if you need access to specific resou...,Single,AAMkAGM1ZDA4MDNjLTUyOWUtNGVlNi04ZmZmLTU5NTU5OD...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2022-07-15,Library Access Orientation,Virtual,30,1,{ PNWU Academic Affiliation: DO,PNWU Status: Fulltime Faculty,Tell us if you need access to specific resou...,Single,AAMkAGM1ZDA4MDNjLTUyOWUtNGVlNi04ZmZmLTU5NTU5OD...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# bookings dataframe info
df_book_all.info()

<class 'pandas.DataFrame'>
Index: 445 entries, 0 to 36
Data columns (total 26 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Date                                  445 non-null    datetime64[us]
 1   Service                               445 non-null    str
 2   Location                              390 non-null    str
 3   Duration (mins.)                      445 non-null    int64
 4   Signed Up Attendees Count             445 non-null    int64
 5    Custom Fields.1                      143 non-null    str
 6    Custom Fields.2                      135 non-null    str
 7    Custom Fields.3                      125 non-null    str
 8   Event Type                            182 non-null    str
 9   Booking Id                            182 non-null    str
 10  Tracking Data                         1 non-null      object
 11   Custom Fields.4                      37 non-null     str
 12   Custom Fields                        107 non-null    str
 13  Column1                               56 non-null     str
 14  Column2                               51 non-null     str
 15  Column3                               51 non-null     str
 16  Column4                               0 non-null      float64
 17  Column5                               0 non-null      float64
 18  Column6                               0 non-null      float64
 19  Column7                               0 non-null      float64
 20  PNWU Status                           160 non-null    str
 21  PNWU Academic Affiliation             143 non-null    str
 22  Virtual/Library Meeting               116 non-null    str
 23  Tell us about your research project   98 non-null     str
 24   PNWU Status                          28 non-null     str
 25  Tells us about your research project  17 non-null     str
dtypes: datetime64[us](1), float64(4), int64(2), object(1), str(18)
memory usage: 93.9+ KB

In [5]:
# bookings dataframe stats
df_book_all.describe().T

,count,mean,min,25%,50%,75%,max,std
Date,445,2023-12-20 06:15:22.247191,2022-07-01 00:00:00,2023-04-03 00:00:00,2023-12-18 00:00:00,2024-09-25 00:00:00,2025-06-25 00:00:00,NaN
Duration (mins.),445.0,57.370787,30.0,60.0,60.0,60.0,60.0,8.492686
Signed Up Attendees Count,445.0,1.013483,1.0,1.0,1.0,1.0,3.0,0.133551
Column4,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Column5,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Column6,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Column7,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# drop columns with null values
df_book_all.drop(['Column4', 'Column5', 'Column6', 'Column7'], axis=1, inplace=True)

In [7]:
df_book_all.head()

,Date,Service,Location,Duration (mins.),Signed Up Attendees Count,Custom Fields.1,Custom Fields.2,Custom Fields.3,Event Type,Booking Id,...,Custom Fields,Column1,Column2,Column3,PNWU Status,PNWU Academic Affiliation,Virtual/Library Meeting,Tell us about your research project,PNWU Status,Tells us about your research project
0,2022-07-01,Research Consultation,Virtual,60,1,{ PNWU Status: Student,PNWU Academic Affiliation: DO,Tell us about your research project in 3 sen...,Single,AAMkAGM1ZDA4MDNjLTUyOWUtNGVlNi04ZmZmLTU5NTU5OD...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-07-06,Research Consultation,Virtual,60,1,{ PNWU Status: Student,PNWU Academic Affiliation: DO,Tell us about your research project in 3 sen...,Single,AAMkAGM1ZDA4MDNjLTUyOWUtNGVlNi04ZmZmLTU5NTU5OD...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022-07-11,Special Project/Collaboration,PNWU Library or Virtual,60,1,{ PNWU Academic Affiliation: Other,PNWU Status: Other,Tell us your idea in 2 sentences or keep it ...,Single,AAMkAGM1ZDA4MDNjLTUyOWUtNGVlNi04ZmZmLTU5NTU5OD...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022-07-12,Library Access Orientation,Virtual,30,1,{ PNWU Academic Affiliation: DO,PNWU Status: Fulltime Faculty,Tell us if you need access to specific resou...,Single,AAMkAGM1ZDA4MDNjLTUyOWUtNGVlNi04ZmZmLTU5NTU5OD...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2022-07-15,Library Access Orientation,Virtual,30,1,{ PNWU Academic Affiliation: DO,PNWU Status: Fulltime Faculty,Tell us if you need access to specific resou...,Single,AAMkAGM1ZDA4MDNjLTUyOWUtNGVlNi04ZmZmLTU5NTU5OD...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Remove whitespace

In [8]:
# remove whitespace at head & tail of string-type columns
for column in df_book_all.columns:
    if df_book_all[column].dtype == 'str':
        df_book_all[column] = df_book_all[column].str.strip()

# remove whitespace from any single-word columns
# single_word_cols_VAERS = list(df_VAERS[['RECVDATE','STATE','RPT_DATE','DIED','DATEDIED','L_THREAT','ER_VISIT','HOSPITAL','X_STAY','DISABLE','BIRTH_DEFECT','RECOVD','VAX_DATE','ONSET_DATE','V_ADMINBY','V_FUNDBY']])
# for col in single_word_cols_VAERS:
    # df_VAERS[col] = df_VAERS[col].replace(" ","")

# Unique string values

In [9]:
# list of unique services
unique_service = list(df_book_all['Service'].unique())
print(unique_service)

['Research Consultation', 'Special Project/Collaboration', 'Library Access Orientation', 'ELEC 704 Bioethics', 'Digital Project Intern', 'ELEC 704 Bioethics Consultation']

In [10]:
# list of unique locations
unique_location = list(df_book_all['Location'].unique())
print(unique_location)

['Virtual', 'PNWU Library or Virtual', nan]

In [11]:
# rename columns for "Custom Fields.1, 2 and 3"
df_book_all.rename(columns={"Custom Fields.1": "Custom1", "Custom Fields.2": "Custom2", "Custom Fields.3" : "Custom3"}, inplace=True)

In [13]:
df_book_all.head()

,Date,Service,Location,Duration (mins.),Signed Up Attendees Count,Custom Fields.1,Custom Fields.2,Custom Fields.3,Event Type,Booking Id,...,Custom Fields,Column1,Column2,Column3,PNWU Status,PNWU Academic Affiliation,Virtual/Library Meeting,Tell us about your research project,PNWU Status,Tells us about your research project
0,2022-07-01,Research Consultation,Virtual,60,1,{ PNWU Status: Student,PNWU Academic Affiliation: DO,Tell us about your research project in 3 sente...,Single,AAMkAGM1ZDA4MDNjLTUyOWUtNGVlNi04ZmZmLTU5NTU5OD...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-07-06,Research Consultation,Virtual,60,1,{ PNWU Status: Student,PNWU Academic Affiliation: DO,Tell us about your research project in 3 sente...,Single,AAMkAGM1ZDA4MDNjLTUyOWUtNGVlNi04ZmZmLTU5NTU5OD...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022-07-11,Special Project/Collaboration,PNWU Library or Virtual,60,1,{ PNWU Academic Affiliation: Other,PNWU Status: Other,Tell us your idea in 2 sentences or keep it a ...,Single,AAMkAGM1ZDA4MDNjLTUyOWUtNGVlNi04ZmZmLTU5NTU5OD...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022-07-12,Library Access Orientation,Virtual,30,1,{ PNWU Academic Affiliation: DO,PNWU Status: Fulltime Faculty,Tell us if you need access to specific resourc...,Single,AAMkAGM1ZDA4MDNjLTUyOWUtNGVlNi04ZmZmLTU5NTU5OD...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2022-07-15,Library Access Orientation,Virtual,30,1,{ PNWU Academic Affiliation: DO,PNWU Status: Fulltime Faculty,Tell us if you need access to specific resourc...,Single,AAMkAGM1ZDA4MDNjLTUyOWUtNGVlNi04ZmZmLTU5NTU5OD...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# list of unique custom fields
unique_custom1 = list(df_book_all['Custom1'].unique())
# unique_custom2 = list(df_book_all['Custom Fields.2'].unique())
# unique_custom3 = list(df_book_all['Custom Fields.3'].unique())
print(unique_custom1)
# print(unique_custom2)
# print(unique_custom3)

# Visualization planning